# Fin 5350 HW-2 
### Collin Butterfield

In [1]:
import numpy as np
from scipy.stats import binom

In [2]:
## Define call and put payoff
def call_payoff(spot, strike):
    return np.maximum(spot - strike, 0.0)

def put_payoff(spot, strike):
    return np.maximum(strike - spot, 0.0)

## Problem 1

In [3]:
def call_prob1(s, k, r, T, v, u, d, n, check = True):
    h = T / n
    spotU = s * u
    spotD = s * d
    Cu = call_payoff(spotU, k)
    Cd = call_payoff(spotD, k)
    delta = (Cu - Cd) / (s * (u - d))
    beta = np.exp(-r * h) * ((u*Cd - d*Cu) / (u - d))
    price = s * delta + beta
    
    return (delta, beta, price)

def put_prob1(s, k, r, T, v, u, d, n, check = True):
    h = T / n
    spotU = s * u
    spotD = s * d
    Cu = put_payoff(spotU, k)
    Cd = put_payoff(spotD, k)
    delta = (Cu - Cd) / (s * (u - d))
    beta = np.exp(-r * h) * ((u*Cd - d*Cu) / (u - d))
    price = s * delta + beta
    
    return (delta, beta, price)



In [4]:
s = 100.0
k = 105.0
r = 0.08
T = 0.5
v = 0.0
u = 1.3
d = 0.8
n = 1.0

call_price = call_prob1(s, k, r, T, v, u, d, n, check = True)
put_price = put_prob1(s, k, r, T, v, u, d, n, check = True)
print("The European Call delta, beta & premium: ")
print(call_price)
print(" ")
print("The European Put delta, beta & premium: ")
print(put_price)

The European Call delta, beta & premium: 
(0.5, -38.431577566092926, 11.568422433907074)
 
The European Put delta, beta & premium: 
(-0.5, 62.451313544901005, 12.451313544901005)


## Problem 2

In [5]:
## verify that the put price is $7.47
s = 100.0
k = 95.0
r = 0.08
T = 0.5
v = 0.0
u = 1.3
d = 0.8
n = 1.0
put_price = put_prob1(s, k, r, T, v, u, d, n, check = True)
print("The European put is:")
print(put_price[2:])

The European put is:
(7.4707881269406045,)


In [6]:
def call_prob2(s, k, r, T, v, u, d, n, check = True):
    h = T / n
    spotU = s * u
    spotD = s * d
    Cu = call_payoff(spotU, k)
    Cd = call_payoff(spotD, k)
    delta = (Cu - Cd) / (s * (u - d))
    beta = np.exp(-r * h) * ((u*Cd - d*Cu) / (u - d))
    price = s * delta + beta
    
    return price

In [7]:
## what is the arbitrage if you have a call price of $17 and $15.50
callp = [17.0, 15.5]
call_price = call_prob2(s, k, r, T, v, u, d, n, check = True)

for i in callp:
    if call_price < i:
        gain = i - call_price
        print("The call price is:", round(call_price, 3), "<", i)
        print("You gain:", round(gain, 3))
        print(" ")
    else:
        loss = call_price - i
        print("The call price is:", round(call_price, 3), ">", i)
        print("You lose:", round(loss, 3))
        print(" ")


The call price is: 16.196 < 17.0
You gain: 0.804
 
The call price is: 16.196 > 15.5
You lose: 0.696
 


## Problem 3

In [8]:
def call_prob3(s, k, r, T, v, u, d, n, check = True):
    h = T / n
    nodes = n + 1
    Ct = np.zeros((nodes, n+1))
    St = np.zeros((nodes, n+1))
    Dt = np.zeros((nodes-1, n))
    Bt = np.zeros((nodes-1, n))
    
    for i in range(nodes):
        St[i, n] = s * (u**(n-i)) * (d**i)
        Ct[i, n] = call_payoff(St[i, n], k)
    

    for t in range((n-1), -1, -1):
        for j in range(t+1):
            St[j, t] = St[j, t+1] / u
            Dt[j, t] = (Ct[j, t+1] - Ct[j+1, t+1]) / (St[j, t] * (u-d))
            Bt[j, t] = np.exp(-r*h) * (((u*Ct[j+1, t+1]) - (d*Ct[j, t+1])) / (u-d))
            Ct[j, t] = (Dt[j, t] * St[j ,t]) + Bt[j, t]
        
    if check:
        print("The Spot matrix:")
        print(St)
        print("\n")
        print("The Delta matrix:")
        print(Dt)
        print("\n")
        print("The B matrix:")
        print(Bt)
        print("\n")
        print("The call price matrix:")
        print(Ct)
                    
            
    return Ct[0,0]
       
    


In [9]:
s = 100
k = 95
r = 0.08
T = 1
v = 0.0
u = 1.3
d = 0.8
n = 2

call_price = call_prob3(s, k, r, T, v, u, d, n, check = True)
print("The call price is:", round(call_price, 3))

The Spot matrix:
[[100. 130. 169.]
 [  0.  80. 104.]
 [  0.   0.  64.]]


The Delta matrix:
[[0.69120742 1.        ]
 [0.         0.225     ]]


The B matrix:
[[-49.12704895 -91.27499672]
 [  0.         -13.83536792]]


The call price matrix:
[[19.99369346 38.72500328 74.        ]
 [ 0.          4.16463208  9.        ]
 [ 0.          0.          0.        ]]
The call price is: 19.994


## Problem 4

In [17]:
## repeat problem 3 with s = 80, 90, 110, 120, 130 and n = 3
k = 95
r = 0.08
T = 1
v = 0.0 # dividend 
u = 1.3
d = 0.8

In [11]:
s = 80
n = 3

call_price = call_prob3(s, k, r, T, v, u, d, n, check = True)
print("The call price is:", round(call_price, 3))

The Spot matrix:
[[ 80.   104.   135.2  175.76]
 [  0.    64.    83.2  108.16]
 [  0.     0.    51.2   66.56]
 [  0.     0.     0.    40.96]]


The Delta matrix:
[[0.48495817 0.70926502 1.        ]
 [0.         0.18181478 0.31634615]
 [0.         0.         0.        ]]


The B matrix:
[[-27.71609813 -51.7930486  -92.50014619]
 [  0.          -9.06395941 -20.50192714]
 [  0.           0.           0.        ]]


The call price matrix:
[[11.08055585 21.9705133  42.69985381 80.76      ]
 [ 0.          2.57218631  5.81807286 13.16      ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]]
The call price is: 11.081


In [12]:
s = 90
n = 3

call_price = call_prob3(s, k, r, T, v, u, d, n, check = True)
print("The call price is:", round(call_price, 3))

The Spot matrix:
[[ 90.   117.   152.1  197.73]
 [  0.    72.    93.6  121.68]
 [  0.     0.    57.6   74.88]
 [  0.     0.     0.    46.08]]


The Delta matrix:
[[0.60899351 0.81717181 1.        ]
 [0.         0.3276473  0.57008547]
 [0.         0.         0.        ]]


The B matrix:
[[-37.61620293 -62.98965805 -92.50014619]
 [  0.         -18.37586909 -41.56469727]
 [  0.           0.           0.        ]]


The call price matrix:
[[ 17.19321255  32.61944411  59.59985381 102.73      ]
 [  0.           5.21473638  11.79530273  26.68      ]
 [  0.           0.           0.           0.        ]
 [  0.           0.           0.           0.        ]]
The call price is: 17.193


In [13]:
s = 110
n = 3

call_price = call_prob3(s, k, r, T, v, u, d, n, check = True)
print("The call price is:", round(call_price, 3))

The Spot matrix:
[[110.   143.   185.9  241.67]
 [  0.    88.   114.4  148.72]
 [  0.     0.    70.4   91.52]
 [  0.     0.     0.    56.32]]


The Delta matrix:
[[0.78940853 0.97412715 1.        ]
 [0.         0.53976733 0.93916084]
 [0.         0.         0.        ]]


The B matrix:
[[-57.41641252 -85.38287694 -92.50014619]
 [  0.         -36.99968843 -83.69023753]
 [  0.           0.           0.        ]]


The call price matrix:
[[ 29.41852594  53.91730574  93.39985381 146.67      ]
 [  0.          10.49983651  23.74976247  53.72      ]
 [  0.           0.           0.           0.        ]
 [  0.           0.           0.           0.        ]]
The call price is: 29.419


In [14]:
s = 120
n = 3

call_price = call_prob3(s, k, r, T, v, u, d, n, check = True)
print("The call price is:", round(call_price, 3))

The Spot matrix:
[[120.   156.   202.8  263.64]
 [  0.    96.   124.8  162.24]
 [  0.     0.    76.8   99.84]
 [  0.     0.     0.    61.44]]


The Delta matrix:
[[0.84194335 1.         1.        ]
 [0.         0.62833492 1.        ]
 [0.         0.         0.12604167]]


The B matrix:
[[-63.68804104 -90.06607416 -92.50014619]
 [  0.         -44.9028274  -92.50014619]
 [  0.           0.          -7.54022244]]


The call price matrix:
[[ 37.34516043  65.93392584 110.29985381 168.64      ]
 [  0.          15.41732511  32.29985381  67.24      ]
 [  0.           0.           2.13977756   4.84      ]
 [  0.           0.           0.           0.        ]]
The call price is: 37.345


In [15]:
s = 130
n = 3

call_price = call_prob3(s, k, r, T, v, u, d, n, check = True)
print("The call price is:", round(call_price, 3))

The Spot matrix:
[[130.   169.   219.7  285.61]
 [  0.   104.   135.2  175.76]
 [  0.     0.    83.2  108.16]
 [  0.     0.     0.    66.56]]


The Delta matrix:
[[0.87636019 1.         1.        ]
 [0.         0.70926502 1.        ]
 [0.         0.         0.31634615]]


The B matrix:
[[-67.35076514 -90.06607416 -92.50014619]
 [  0.         -51.7930486  -92.50014619]
 [  0.           0.         -20.50192714]]


The call price matrix:
[[ 46.57605995  78.93392584 127.19985381 190.61      ]
 [  0.          21.9705133   42.69985381  80.76      ]
 [  0.           0.           5.81807286  13.16      ]
 [  0.           0.           0.           0.        ]]
The call price is: 46.576


In [16]:
## Conclusion: We can see that as stock price rises, we will also see delta rise

## Problem 5

In [67]:
def euro_binom_pricer(s, k, r, v, q, T, n, payoff, check = True):
    nodes = n  + 1
    h = T / n
    u = np.exp((r - v) * h + q * np.sqrt(h))
    d = np.exp((r - v) * h - q * np.sqrt(h))
    pu = (np.exp((r - v) * h) - d) / (u - d)
    pd = 1.0 - pu
    disc = np.exp(-r * h)
    
    
    ## Arrays to store the spot prices and option values
    Ct = np.zeros((nodes, n+1))
    St = np.zeros((nodes, n+1))
    
    for i in range(nodes):
        St[i, n] = s * (u ** (n - i)) * (d ** i)
        Ct[i, n] = payoff(St[i, n], k)
        
    for t in range((n - 1), -1, -1):
        for j in range(t+1):
            St[j, t] = St[j, t+1] / u
            Ct[j, t] = disc * (pu * Ct[j, t+1] + pd * Ct[j+1, t+1])
           
    if check:
        print("The spot matrix:")
        print(St)
        print(" ")
        print("The premium matrix:")
        print(Ct)
                     
    return Ct[0,0]

In [68]:
def amer_binom_pricer(s, k, r, v, q, T, n, payoff, check = True):
    nodes = n  + 1
    h = T / n
    u = np.exp((r - v) * h + q * np.sqrt(h))
    d = np.exp((r - v) * h - q * np.sqrt(h))
    pu = (np.exp((r - v) * h) - d) / (u - d)
    pd = 1.0 - pu
    disc = np.exp(-r * h)
    
    
    ## Arrays to store the spot prices and option values
    Ct = np.zeros((nodes, n+1))
    St = np.zeros((nodes, n+1))
    
    for i in range(nodes):
        St[i, n] = s * (u ** (n - i)) * (d ** i)
        Ct[i, n] = payoff(St[i, n], k)
        
    for t in range((n - 1), -1, -1):
        for j in range(t+1):
            St[j, t] = St[j, t+1] / u
            Ct[j, t] = disc * (pu * Ct[j, t+1] + pd * Ct[j+1, t+1])
            # St[j] = St[j] / u
            Ct[j, t] = np.maximum(Ct[j, t], payoff(St[j, t], k))
    if check:
        print("The spot matrix:")
        print(St)
        print(" ")
        print("The premium matrix:")
        print(Ct)
                     
    return Ct[0,0]

In [89]:
s = 100
k = 95
r = 0.08
q = 0.3 # sigma
v = 0.0 # dividend
T = 1
n = 3

euro_call_price = euro_binom_pricer(s, k, r, v, q, T, n, call_payoff, check = True)
print("The euro call premium is:",round(euro_call_price, 3))
print("\n")
amer_call_price = amer_binom_pricer(s, k, r, v, q, T, n, call_payoff, check = True)
print("The american call premium is:",round(amer_call_price, 3))
print("\n")
euro_put_price = euro_binom_pricer(s, k, r, v, q, T, n, put_payoff, check = True)
print("The euro put premium is:",round(euro_put_price, 3))
print("\n")
amer_put_price = amer_binom_pricer(s, k, r, v, q, T, n, put_payoff, check = True)
print("The american put premium is:",round(amer_put_price, 3))

The spot matrix:
[[100.         122.12461202 149.1442086  182.1417861 ]
 [  0.          86.36925537 105.47811803 128.8147424 ]
 [  0.           0.          74.59648274  91.10066512]
 [  0.           0.           0.          64.42842668]]
 
The premium matrix:
[[18.28255221 33.14931753 56.64406241 87.1417861 ]
 [ 0.          6.6897296  15.04032855 33.8147424 ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]]
The euro call premium is: 18.283


The spot matrix:
[[100.         122.12461202 149.1442086  182.1417861 ]
 [  0.          86.36925537 105.47811803 128.8147424 ]
 [  0.           0.          74.59648274  91.10066512]
 [  0.           0.           0.          64.42842668]]
 
The premium matrix:
[[18.28255221 33.14931753 56.64406241 87.1417861 ]
 [ 0.          6.6897296  15.04032855 33.8147424 ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]]
The american call premium is: 18.28

In [90]:
if euro_call_price == amer_call_price:
    print("The call premiums are the SAME:", round(amer_call_price,3))
    print("Since there is no dividend, there will be no early exercise; the call premiums will be the same")
else:
    print("They are not the same")
print("\n")

if euro_put_price == amer_put_price:
    print("The put premiums are the SAME:", round(amer_put_price,3))
else:
    print("""The put premiums are NOT the same:
    We chose to exercise early""")
    print("American",round(amer_put_price,3), "!=", "European",round(euro_put_price,3))

The call premiums are the SAME: 18.283
Since there is no dividend, there will be no early exercise; the call premiums will be the same


The put premiums are NOT the same:
    We chose to exercise early
American 6.678 != European 5.979


In [86]:
## Put Call Parity???
a = euro_call_price - euro_put_price
print(a)
h = T/n
F = s * np.exp(r * T)
disc = np.exp(-r * h)
b = disc*(F-k)
print(b)

if a == b:
    print("The put call parity holds")
else:
    print("The put call parity does NOT hold")

12.30394709326959
12.977971836817542
The put call parity does NOT hold


## Problem 6

In [93]:
s = 40
k = 40
r = 0.08
q = 0.3 # sigma
v = 0.0 # dividend
T = 0.5
n = 3
h = T/n
u = np.exp((r - v) * h + q * np.sqrt(h))
d = np.exp((r - v) * h - q * np.sqrt(h))
print("u =", u)
print(" ")
print("d =", d)
print("\n")

euro_call_price = euro_binom_pricer(s, k, r, v, q, T, n, call_payoff, check = True)
print("The euro call premium is:",round(euro_call_price, 3))
print("\n")
amer_call_price = amer_binom_pricer(s, k, r, v, q, T, n, call_payoff, check = True)
print("The american call premium is:",round(amer_call_price, 3))
print("\n")
euro_put_price = euro_binom_pricer(s, k, r, v, q, T, n, put_payoff, check = True)
print("The euro put premium is:",round(euro_put_price, 3))
print("\n")
amer_put_price = amer_binom_pricer(s, k, r, v, q, T, n, put_payoff, check = True)
print("The american put premium is:",round(amer_put_price, 3))

u = 1.1454617381452392
 
d = 0.8966038495199921


The spot matrix:
[[40.         45.81846953 52.48330374 60.11761633]
 [ 0.         35.86415398 41.08101616 47.05673217]
 [ 0.          0.         32.15593852 36.83339723]
 [ 0.          0.          0.         28.83113826]]
 
The premium matrix:
[[ 4.37742951  7.73902974 13.01309727 20.11761633]
 [ 0.          1.51406624  3.26869392  7.05673217]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]]
The euro call premium is: 4.377


The spot matrix:
[[40.         45.81846953 52.48330374 60.11761633]
 [ 0.         35.86415398 41.08101616 47.05673217]
 [ 0.          0.         32.15593852 36.83339723]
 [ 0.          0.          0.         28.83113826]]
 
The premium matrix:
[[ 4.37742951  7.73902974 13.01309727 20.11761633]
 [ 0.          1.51406624  3.26869392  7.05673217]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]]
The american call 

## The End